specVersion: "1.0.0"

name: "uniswap-v3"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your
  new Ethereum SubQuery project"
repository: "https://github.com/subquery/ethereum-subql-starter"

schema:
  file: "./schema.graphql"

network:
  chainId: "1"
  dictionary: "https://eth-dict.api.onfinality.io/"
  endpoint: "wss://eth.api.onfinality.io/ws?apikey="
dataSources:
  - kind: ethereum/Runtime
    startBlock: 6175243
    options:
      # Must be a key of assets
      abi: gravity
      address: "0x2E645469f354BB4F5c8a05B3b30A929361cf77eC"
    assets:
      gravity:
        file: "./abis/Gravity.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleNewGravatar
          kind: ethereum/LogHandler
          filter:
            topics:
              - NewGravatar(uint256,address,string,string)
        - handler: handleUpdatedGravatar
          kind: ethereum/LogHandler
          filter:
            topics:
              - UpdatedGravatar(uint256,address,string,string)
